# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /blog/projects/microbam
      - name: OurLegacy
        link: /blog/projects/ourlegacy
  - name: Tags
    link: /blog/tags
  - name: About
    link: /blog/about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/alainpham
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/alainpham
      - name: Twitter
        icon: twitter
        link: https://twitter.com/koint
    
